== Use `secrets` For Cryptographic Randomness

Many developers who want a random value such as a generated password or token,
will reach towards the `random` module.  The `random` module is widely used,
familiar to most users of Python, and usually feels "good enough" at being
unpredictable.

However, for actual cryptographic needs, `random` falls short.  When a seed is
not specified to `random.seed()`, a small number of truly random entropy
bytes are used as a seed.  In many circumstances that makes a "random" token
sufficiently unpredictable.

Many circumstances are not _all circumstances_, and for applications that care
about cryptographic security, it is better simply to start by using `secrets`
in case your code becomes used in a situation where vulnerabilities are
exposed.  The `secrets` module has been available since Python 3.6, so is not
anything very new.

An excellent, fairly informal, analysis of vulnerabilities in the Mersenne
Twister was done by James Roper.footnote:[See Roper's _Cracking Random Number
Generators - Part 3_ at
https://jazzy.id.au/2010/09/22/cracking_random_number_generators_part_3.html,
and _Cracking Random Number Generators - Part 4_ at
https://jazzy.id.au/2010/09/25/cracking_random_number_generators_part_4.html.]
The short summary is that if you can observe 624 consecutive integers produced
by the Mersenne Twister, you can  reconstruct its complete state, and thereby
every output it will produce in the future.  Even if fewer consecutive values
can be observed by a malicious intruder, indirect vulnerabilities can likely
be exploited.

Besides the vulnerability Rober points out, we also commonly spin up virtual
images with little initial entropy and/or reproducing an exact known state of
the MT generator.  Running on your local machine which has been in operation
for hours or weeks provides sufficient strength in a generated seed. Running on
a Docker image Kubernetes spins up frequently, or on an AWS Lambda or Google
Cloud Function very well may not.  

The code you run today in a circumstance where "+++<code>random</code>+++
is fine" will probably be ported to an environment where it is not tomorrow.

There are only a few functions in the `secrets` module.  The most commonly
used one generate tokens of arbitrary length in a few different formats:

[source,python]
----
>>> secrets.token_bytes(12)
b'\xe7Wt\x96;\x829a\xc9\xbd\xe1\x94'
>>> secrets.token_hex(20)
'b397afc44c9cac5dba7900ef615ad48dd351d7e3'
>>> secrets.token_urlsafe(24)
'QYNBxUDVGO4feQUyetyih8V5vKKyy8nQ'
----

For security against by brute-force attacks by state-level actors, a length of
at least 32 is recommended.  A few additional functions are available as well,
specifically `secrets.choice()`, `secrets.randbelow()`, and
`secrets.randbits()`, but not the full range of distributions and other types
of pseudo-randomness that `random` provides.  

The very interesting `secrets.compare_digest()` is also present which will
compare two string or bytes values in constant time to avoid timing attacks.
This situation is a very specific threat model, which only occasionally
exists.  That said, if you are comparing tokens rather than simply generic
strings, there is no harm in using this function rather than a simple `==`
just in case you've overlooked such an attack.

