== Putting Passwords Or Other Secrets In "Secure" Source Code

Far too often, I have seen password information included within the source
code of project files.  Usually when this is done, developers have carelessly
thought that in their particular scenario, these source code files will not be
directly exposed to users, so this style does not matter.

Often the systems in question are webservers or other kinds of data servers,
where in normal operation access is only via URLs or other encapsulate
mechanisms.  The passwords in source code are used to access additional
resources, such as other websites or databases protected by credentials.  Such
developers often try to reassure themselves by asserting that the resource is
itself inside a firewall zone or otherwise whitelists the particular
applications or servers making such requests.

Approaching secrets this way is *always* a bad idea, and is usually motivated
by mere laziness (although ignorance can certainly be in play as well).  The
assumptions you make about underlying source code not being exposed to
malicious actors almost inevitably winds being proved wrong, through one
mechanism or another.  Sometimes that happens by so-called "hackers"
deliberately looking for exploits; probably even more often it occurs simply
because access to the source code is not well regulated within version control
systems, shared drives, backup storage, and so on.

A typical example of this mistake can resemble the below.  This example uses
an HTTPS request, but a very similar pattern would apply to a request using
Python's DB-API to talk to a database that uses credentials.

.Insecure and badly designed credential storage
[source,python]
----
import requests
from requests.auth import HTTPBasicAuth

def get_other_data():
    _username = "DavidMertz"
    _password = "jNeyQIyE6@pR"
    _localservice1 = "192.168.227.1
    _localservice2 = "192.168.227.2
    _localservice3 = "192.168.227.3

    for service in [_localservice1, _localservice2, _localservice3]:
        resp = requests.get(f"https://{service}/latest-data",
                            auth = HTTPBasicAuth(_username, _password))
        if resp.status_code == 200:
            data = process(resp.text)
            break

    return data
----

The same general principles apply for passwords, tokens, session keys, or any
other information that should generally be kept secure.

A first, and sometimes adequate, approach is to store secrets in environment
variables.  For example:

.User environment variables to store secrets semi-securely
[source,python]
----
import os

def get_other_data():
    _username = os.environ.get("LOCAL_SERVICE_USER")
    _password = os.environ.get("LOCAL_SERVICE_PASSWORD")
    _localservice1 = os.environ.get("LOCAL_SERVICE_ADDR_1")
    _localservice2 = os.environ.get("LOCAL_SERVICE_ADDR_2")
    _localservice3 = os.environ.get("LOCAL_SERVICE_ADDR_3")
    
    # ... rest of code ...
----

This becomes a vulnerability only if an attacker can gain shell access, or
equivalent, to a system where the code is running.  However, these secrets are
visible in unencrypted form within an OS shell.  Developers (myself included)
often lose track of which environment variables were previously set, and thereby
forget explicitly to unset them after an application using them has terminated.

A step better is to use the "dotenv" approach.  This style _does_ keep secret
information within a file on the filesystem, usually with the special name
`.env`.  Specifically, this file must always be excluded from being kept under
version control (e.g. in `.gitignore`), and should be distributed by a
separate secure channel, as needed.  As well, permissions to a `.env` file
should be restricted to the specific user or group that has legitimate access
rights.

.Using dotenv for storing secrets semi-securely in filesystem
[source,python]
----
# pip install python-dotenv
import os
from os.path import join, dirname
from dotenv import load_dotenv

dotenv_path = join(dirname(__file__), ".env")
load_dotenv(dotenv_path)

def get_other_data():
    _username = os.environ.get("LOCAL_SERVICE_USER")
    _password = os.environ.get("LOCAL_SERVICE_PASSWORD")
    _localservice1 = os.environ.get("LOCAL_SERVICE_ADDR_1")
    _localservice2 = os.environ.get("LOCAL_SERVICE_ADDR_2")
    _localservice3 = os.environ.get("LOCAL_SERVICE_ADDR_3")
    
    # ... rest of code ...
----

This looks very similar to directly loading environment variables; it is,
since the code is identical.  However, these environment variables are only
loaded at the time this code runs, and are not in the environment of the
parent process.

The `.env` file used in this example would look like:

[source,shell]
----
# Local service settings
LOCAL_SERVICE_USER=DavidMertz
LOCAL_SERVICE_PASSWORD="jNeyQIyE6@pR"
LOCAL_SERVICE_PREFIX=192.168.227
LOCAL_SERVICE_ADDR_1=${LOCAL_SERVICE_PREFIX}.1
LOCAL_SERVICE_ADDR_2=${LOCAL_SERVICE_PREFIX}.2
LOCAL_SERVICE_ADDR_3=${LOCAL_SERVICE_PREFIX}.3
----

A better approach still is to use your operating system's keyring service.
This is handled somewhat differently by macOS, Windows, Linux, and even
Android, but all have secure systems that do not store plaintext passwords.
The module `keyring` wraps those OS-specific details and provides a common
interface in Python:

.Using `keyring` for storing secrets securely
[source,python]
----
# pip install keyring
import keyring as kr

def get_other_data():
    _username = kr.get_password("data-service", "user")  # (1)
    _password = kr.get_password("data-service", "pw")
    _localservice1 = kr.get_password("data-service", "1")
    _localservice2 = kr.get_password("data-service", "2")
    _localservice1 = kr.get_password("data-service", "3")

    # ... rest of code ...
----

(1) Must have previously run `kr.set_password("data-service", "user", "DavidMertz")`
on the system running code.

Using the `keyring` module is straightforward, and will not keep unencrypted
versions of any secrets anywhere on your filesystem. If at all possible, use
this final approach.  However, the first two solutions are still *vastly*
better than putting secrets directly into source code.
